name: CI

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'release'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['5.4']
        mysql-version: ['5.5']

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Start MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql-version: ${{ matrix.mysql-version }}
        mysql-database: 'test'
        mysql-root-password: 'root'

    - name: Run tests
      run: php test/index.php
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: test
        DB_USERNAME: root
        DB_PASSWORD: root

  package:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Create Zip Archive
      run: zip -r deployable.zip . -x ".git/*" ".github/*" "test/*" ".travis.yml" "_howto/*" "_sql_upgrades/*" "_sql_utilities/*"
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./deployable.zip
        asset_name: deployable.zip
        asset_content_type: application/zip
